namespace: ecommerce
replicas: 2
image:
  repository: 163841615263.dkr.ecr.eu-north-1.amazonaws.com/product-catalog
  tag: v1.0.0-abca63e
service:
  port: 80
  targetPort: 3000
env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "3000"
  - name: MONGODB_URI
    valueFrom:
      configMapKeyRef:
        name: product-catalog-config
        key: MONGODB_URI
livenessProbe:
  path: /health/
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  path: /health/
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
