# ============================================
# RESOURCE: Deployment
# SERVICE: Checkout Service (FastAPI)
# PURPOSE: Runs Checkout Service API microservice
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  labels:
    app: checkout-service
    tier: backend
    language: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
      tier: backend
  template:
    metadata:
      labels:
        app: checkout-service
        tier: backend
    spec:
      containers:
        - name: checkout-service
          image: 163841615263.dkr.ecr.eu-north-1.amazonaws.com/checkout-service:v1.0.0-46ccac4
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "0.25"
          
          env:
            - name: ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
