apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout-service
  namespace: argocd
spec:
  project: ecommerce
  source:
    repoURL: https://github.com/lukaszjakubowski/ecom-devops
    targetRevision: main
    path: charts/microservice
    helm:
      valueFiles:
        - ../../helmfiles/checkout-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
