apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Values.namespace | default "ecommerce" }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: db
  selector:
    {{- include "database.labels" . | nindent 4 }}
