apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Values.namespace | default "ecommerce" }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "database.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "database.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "database.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "database.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
              name: db
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: {{ include "database.fullname" . }}-data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "database.fullname" . }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
