{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "ecommerce" }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
