name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:          # Adjust to the branch(s) you protect
    branches: [ main ]
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply after merge (true/false)"
        required: false
        default: "false"


permissions:
  id-token: write   # required for OIDC token generation
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.0"
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::163841615263:role/terraform-github-role
          aws-region: eu-north-1
      - name: Verify OIDC authentication
        run: aws sts get-caller-identity
      - name: Terraform Init (remote backend)
        run: terraform -chdir=infra/terraform init -upgrade -reconfigure
      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan
      - name: Terraform Apply
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.apply == 'true' }}
        run: terraform -chdir=infra/terraform apply --auto-approve